const zones = {
  "Agew Awi Zone": [
    "Ankasha Guagusa",
    "Banja Shekudad",
    "Dangila",
    "Faggeta Lekoma",
    "Guagusa Shekudad",
    "Guangua ",
    "Jawi",
  ],
  "East Gojjam Zone": [
    "Aneded",
    "Awabel",
    "Baso Liben",
    "Bibugn",
    "Debay Telatgen",
    "Debre Elias",
    "Debre",
    "Markos Town",
    "Dejen",
    "Enarj Enawga",
    "Enbise Sar Midir",
    "Enemay",
    "Goncha",
    "Goncha Siso Enese",
    "Gozamin",
    "Hulet Ej Enese",
    "Machakel",
    "Shebel Berenta",
    "Sinan",
  ],
  "North Gondar Zone": [
    "Addi Arkay",
    "Alefa",
    "Beyeda",
    "Chilga",
    "Dabat",
    "Debarq",
    " Dembiya",
    "Gondar Town",
    "Gondar Zuria",
    "Jan Amora",
    "Lay Armachiho",
    "Metemma",
    "Mirab Armachiho",
    "Mirab Belessa",
    "Misraq Belessa",
    "Qwara",
    "Tach Armachiho",
    "Takusa",
    "Tegeda",
    "Tselemt",
    "Wegera",
  ],
  "North Shewa Zone": [
    "Angolalla Tera",
    "Ankober",
    "Antsokiyana Gemza",
    " Asagirt",
    "Basona Werana",
    "Berehet",
    "Debre Birhan Town",
    "Efratana Gidim",
    "Ensaro",
    "Gishe",
    "Hagere Mariamna Kesem",
    "Kewet",
    "Menjarna Shenkora",
    "Menz Gera Midir",
    "Menz Keya Gebreal",
    "Menz Lalo Midir",
    "Menz Mam Midir",
    "Merhabete",
    "Mida Woremo",
    "Mojana Wadera",
    "Moretna Jiru",
    "Siyadebrina Wayu",
    "Termaber",
  ],
  "North Wollo Zone": [
    "Bugna",
    "Dawunt",
    "Delanta",
    "Gidan",
    "Guba Lafto",
    "Habru",
    "Kobo",
    "Lasta",
    "Meket",
    "Wadla",
    " Weldiya Town",
  ],
  "Oromia Zone": [
    "Artuma Fursi",
    " Baati",
    "Dawa Chaffa",
    "Dawa Harewa",
    "Jilee Dhummuugaa",
    " Kemise Town",
  ],
  "South Gondar Zone": [
    "Debre Tabor Town",
    "Dera ",
    "Ebenat",
    "Farta",
    "Fogera",
    "Lay Gayint",
    "Libo Kemekem",
    "Mirab Este",
    "Misraq Este",
    "Simada",
    "Tach Gayint",
  ],
  "South Wollo Zone": [
    "Abuko",
    "Amba Sel",
    "Debre Sina",
    "Dessie Town",
    "Dessie Zuria",
    "Jama",
    "Kalu",
    "Kelela",
    "Kombolcha Town",
    "Kutaber",
    "Legahida",
    "Legambo",
    "Magdala",
    " Mehal Sayint",
    "Sayint",
    "Tehuledere",
    "Tenta",
    "Wegde",
    "Were Babu",
    "Were Ilu",
  ],
  "Wag Hemra Zone": [
    "Abergele",
    "Dehana",
    "Gazbibla ",
    "Sehala",
    " Soqota ",
    "Soqota Town",
    "Zikuala",
  ],
  "West Gojjam Zone": [
    "Bahir Dar Zuria",
    "Bure ",
    "Dega Damot",
    "Debub Achefer ",
    "Dembecha",
    "Jabi Tehnan",
    "Finote Selam Town",
    "Kuarit",
    "Mecha",
    "Sekela",
    "Semien Achefer",
    "Wemberma",
    "Yilmana Densa",
  ],
  "Bahir Dar": ["Bahir Dar"],
  Argobba: ["Argobba"],
};

export default zones;
